import Link from "next/link";
import { Icon } from "@/components/Icon";

const features = [
  ["trend", "See the numbers clearly", "Turn income and expenses into transparent surplus, savings-rate, and emergency-fund metrics."],
  ["chat", "Ask in plain language", "Choose an explainable rule engine or an intent-aware AI assistant for clear educational guidance."],
  ["target", "Turn plans into progress", "Set financial goals, understand the remaining gap, and focus on the next realistic action."],
] as const;

export default function Home() {
  return <main className="landing-page">
    <section className="container hero"><div className="hero-copy"><div className="hero-kicker"><span><Icon name="spark"/></span> AI-powered personal finance guidance</div><h1>Make your money<br/><em>make sense.</em></h1><p className="lede">Understand your cash flow, build better financial habits, and ask questions in plain language—with calculations you can inspect and guidance that avoids hype.</p><div className="actions"><Link className="button large" href="/register">Build your financial picture <Icon name="arrow"/></Link><Link className="text-action hero-login" href="/login">Already have an account? Log in</Link></div><div className="trust-row"><span>✓ No bank connection</span><span>✓ Explainable metrics</span><span>✓ Private history</span></div></div>
    <div className="hero-product" aria-label="Illustrative Wealth Assistant dashboard preview"><div className="preview-top"><div><span className="preview-logo"><Icon name="trend"/></span><strong>Monthly overview</strong></div><span className="preview-period">This month</span></div><div className="preview-balance"><span>Estimated monthly surplus</span><strong>$1,240</strong><small>+13.8% savings rate</small></div><div className="preview-metrics"><div><span>Income</span><strong>$6,200</strong></div><div><span>Expenses</span><strong>$4,960</strong></div><div><span>Reserve</span><strong>72%</strong></div></div><div className="preview-goal"><div><span className="goal-icon"><Icon name="target"/></span><div><strong>Emergency reserve</strong><span>$8,600 of $12,000</span></div><b>72%</b></div><div className="progress"><span style={{width:"72%"}}/></div></div><div className="preview-chat"><span className="chat-avatar"><Icon name="spark"/></span><p><strong>Wealth AI</strong>Your surplus is positive. Building the remaining reserve gap before increasing investing would strengthen your short-term flexibility.</p></div><span className="preview-caption">Illustrative preview · Educational guidance</span></div></section>
    <section className="identity-strip"><div className="container"><span>One financial picture</span><i/><span>Two assistant modes</span><i/><span>Zero bank credentials</span></div></section>
    <section className="container features"><div className="section-heading"><div><p className="eyebrow">Built for financial clarity</p><h2>Guidance grounded in your numbers.</h2></div><p>The assistant keeps deterministic calculations separate from generated explanations, labels assumptions, and never pretends to execute trades or know live prices.</p></div><div className="feature-grid">{features.map(([icon,t,d],index)=><article className="feature-card" key={t}><span className="feature-icon"><Icon name={icon} size={22}/></span><span className="feature-number">0{index+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="container closing-cta"><span className="closing-mark"><Icon name="spark" size={28}/></span><div><p className="eyebrow">A calmer place to start</p><h2>Clarity before complexity.</h2><p>Build your profile in minutes, then use the dashboard and assistant to explore your next step.</p></div><Link className="button large" href="/register">Create your workspace <Icon name="arrow"/></Link></section>
  </main>;
}
