"use client";

import { FormEvent, useEffect, useState } from "react";
import { Protected } from "@/components/Protected";
import { api, formatMoney } from "@/lib/api";
import { Icon } from "@/components/Icon";
import { ErrorPanel, LoadingPanel } from "@/components/StatusPanel";

type UserProfile={display_name:string;preferred_currency:string;timezone:string;financial_literacy:string;avatar_url:string|null};
type Goal={id?:string;name:string;target_amount:number;current_amount:number;target_date?:string|null};
type FinancialProfile={monthly_income:number;monthly_expenses:number;current_savings:number;monthly_investment:number;risk_tolerance:string;investment_horizon_months:number;goals:Goal[]};
const initialUser:UserProfile={display_name:"",preferred_currency:"USD",timezone:"UTC",financial_literacy:"beginner",avatar_url:null};
const initialFinancial:FinancialProfile={monthly_income:0,monthly_expenses:0,current_savings:0,monthly_investment:0,risk_tolerance:"moderate",investment_horizon_months:60,goals:[]};

export default function ProfilePage(){
 const [profile,setProfile]=useState(initialUser);const [financial,setFinancial]=useState(initialFinancial);const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError("");try{const [p,f]=await Promise.all([api<UserProfile>("/profile"),api<FinancialProfile>("/financial-profile")]);setProfile(p);setFinancial(f);}catch(e){setError(e instanceof Error?e.message:"Unable to load profile");}finally{setLoading(false);}}
 useEffect(()=>{void Promise.all([api<UserProfile>("/profile"),api<FinancialProfile>("/financial-profile")]).then(([p,f])=>{setProfile(p);setFinancial(f);}).catch(e=>setError(e instanceof Error?e.message:"Unable to load profile")).finally(()=>setLoading(false));},[]);
 async function save(e:FormEvent){e.preventDefault();setMessage("");setError("");if(financial.goals.some(g=>!g.name.trim()||g.target_amount<=0)){setError("Each goal needs a name and a target amount greater than 0.");return;}setBusy(true);try{await Promise.all([api("/profile",{method:"PUT",body:JSON.stringify(profile)}),api("/financial-profile",{method:"PUT",body:JSON.stringify(financial)})]);setMessage("Profile saved. Your dashboard and assistant now use these values.");}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save");}finally{setBusy(false);}}
 function numberField(key:keyof Pick<FinancialProfile,"monthly_income"|"monthly_expenses"|"current_savings"|"monthly_investment"|"investment_horizon_months">,label:string,help:string){const horizon=key==="investment_horizon_months";return <div className="field"><label htmlFor={key}>{label}</label><div className={horizon?"input-suffix":"money-input"}>{!horizon&&<span aria-hidden="true">{profile.preferred_currency}</span>}<input id={key} type="number" min={horizon?"1":"0"} max={horizon?"1200":undefined} step={horizon?"1":"0.01"} required value={financial[key]} onChange={e=>setFinancial({...financial,[key]:Number(e.target.value)})}/>{horizon&&<span>months</span>}</div><small>{help}</small></div>}
 function addGoal(){setFinancial({...financial,goals:[...financial.goals,{name:"",target_amount:0,current_amount:0,target_date:null}]});}
 function updateGoal(index:number,patch:Partial<Goal>){setFinancial({...financial,goals:financial.goals.map((goal,i)=>i===index?{...goal,...patch}:goal)});}
 function removeGoal(index:number){setFinancial({...financial,goals:financial.goals.filter((_,i)=>i!==index)});}
 const surplus=financial.monthly_income-financial.monthly_expenses;
 return <Protected><main className="container profile-page"><div className="page-head"><div><p className="eyebrow">Your financial foundation</p><h1>Financial profile</h1><p className="page-subtitle">Use approximate monthly figures. You can update them whenever life changes.</p></div><div className="privacy-chip"><span>✓</span> No bank credentials needed</div></div>
 {loading&&<LoadingPanel label="Loading your financial profile"/>}{!loading&&error&&!financial.monthly_income&&<ErrorPanel message={error} onRetry={()=>void load()}/>} {!loading&&<form className="profile-layout" onSubmit={save}>
  <div className="profile-sections">
   <section className="card profile-section"><div className="section-title"><span><Icon name="profile"/></span><div><p className="eyebrow">About you</p><h2>Workspace preferences</h2></div></div><div className="field-grid three"><div className="field"><label htmlFor="display_name">Display name</label><input id="display_name" maxLength={80} value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})} placeholder="How should we greet you?"/></div><div className="field"><label htmlFor="currency">Currency</label><input id="currency" minLength={3} maxLength={3} required value={profile.preferred_currency} onChange={e=>setProfile({...profile,preferred_currency:e.target.value.toUpperCase()})} aria-describedby="currency-help"/><small id="currency-help">Three-letter code, such as USD.</small></div><div className="field"><label htmlFor="literacy">Financial familiarity</label><select id="literacy" value={profile.financial_literacy} onChange={e=>setProfile({...profile,financial_literacy:e.target.value})}><option value="beginner">Beginner — explain concepts</option><option value="intermediate">Intermediate — balanced detail</option><option value="advanced">Advanced — concise detail</option></select></div></div></section>
   <section className="card profile-section"><div className="section-title"><span><Icon name="trend"/></span><div><p className="eyebrow">Cash flow</p><h2>Your monthly picture</h2></div></div><p className="section-description">These values power your surplus, savings rate, reserve target, and recommendations.</p><div className="field-grid">{numberField("monthly_income","Monthly income","Take-home income across reliable sources.")}{numberField("monthly_expenses","Monthly expenses","Essential and flexible spending combined.")}{numberField("current_savings","Liquid savings","Money accessible for emergencies.")}{numberField("monthly_investment","Planned monthly investing","A plan—not an automatic transaction.")}{numberField("investment_horizon_months","Investment horizon","How long before you expect to use invested money.")}</div></section>
   <section className="card profile-section"><div className="section-title"><span><Icon name="target"/></span><div><p className="eyebrow">Comfort with uncertainty</p><h2>Risk profile</h2></div></div><p className="section-description">Choose the description closest to how you would respond to market losses. This is educational context, not a suitability assessment.</p><div className="risk-options" role="radiogroup" aria-label="Risk tolerance">{[["conservative","Protect stability","Prefer smaller fluctuations and easier access to funds."],["moderate","Balance growth and stability","Accept some fluctuation for long-term growth."],["aggressive","Prioritize long-term growth","Can tolerate substantial short-term declines."]].map(([value,title,description])=><label className={financial.risk_tolerance===value?"selected":""} key={value}><input type="radio" name="risk" value={value} checked={financial.risk_tolerance===value} onChange={e=>setFinancial({...financial,risk_tolerance:e.target.value})}/><span className="radio-mark"/><span><strong>{title}</strong><small>{description}</small></span></label>)}</div></section>
   <section className="card profile-section goals-editor"><div className="card-heading"><div className="section-title"><span><Icon name="target"/></span><div><p className="eyebrow">Purposeful saving</p><h2>Financial goals</h2></div></div><button className="button secondary compact" type="button" onClick={addGoal}>+ Add goal</button></div><p className="section-description">Track up to 20 goals. Progress appears on your dashboard.</p>{financial.goals.length===0?<div className="inline-empty"><span><Icon name="target"/></span><div><strong>No goals yet</strong><p>Add a home deposit, emergency reserve, travel plan, education target, or another goal that matters to you.</p></div></div>:<div className="goal-editor-list">{financial.goals.map((goal,index)=><fieldset key={goal.id??index}><legend>Goal {index+1}</legend><div className="field goal-name"><label htmlFor={`goal-name-${index}`}>Goal name</label><input id={`goal-name-${index}`} required maxLength={100} value={goal.name} onChange={e=>updateGoal(index,{name:e.target.value})} placeholder="e.g. Emergency reserve"/></div><div className="field"><label htmlFor={`goal-target-${index}`}>Target amount</label><div className="money-input"><span aria-hidden="true">{profile.preferred_currency}</span><input id={`goal-target-${index}`} type="number" min="0.01" step="0.01" required value={goal.target_amount||""} onChange={e=>updateGoal(index,{target_amount:Number(e.target.value)})}/></div></div><div className="field"><label htmlFor={`goal-current-${index}`}>Saved so far</label><div className="money-input"><span aria-hidden="true">{profile.preferred_currency}</span><input id={`goal-current-${index}`} type="number" min="0" step="0.01" required value={goal.current_amount} onChange={e=>updateGoal(index,{current_amount:Number(e.target.value)})}/></div></div><div className="field"><label htmlFor={`goal-date-${index}`}>Target date <small>Optional</small></label><input id={`goal-date-${index}`} type="date" value={goal.target_date??""} onChange={e=>updateGoal(index,{target_date:e.target.value||null})}/></div><button className="icon-button danger" type="button" aria-label={`Remove goal ${index+1}`} onClick={()=>removeGoal(index)}>×</button></fieldset>)}</div>}</section>
  </div>
  <aside className="profile-summary"><div className="card"><p className="eyebrow">Live preview</p><h2>Monthly snapshot</h2><div className="summary-surplus"><span>Estimated surplus</span><strong className={surplus<0?"negative":""}>{formatMoney(surplus,profile.preferred_currency||"USD")}</strong></div><div className="summary-row"><span>Income</span><strong>{formatMoney(financial.monthly_income,profile.preferred_currency||"USD")}</strong></div><div className="summary-row"><span>Expenses</span><strong>{formatMoney(financial.monthly_expenses,profile.preferred_currency||"USD")}</strong></div><div className="summary-row"><span>Planned investing</span><strong>{formatMoney(financial.monthly_investment,profile.preferred_currency||"USD")}</strong></div><div className="summary-row"><span>Goals</span><strong>{financial.goals.length}</strong></div><div className="summary-note"><Icon name="spark"/><p>Saving updates recalculates your dashboard and gives both assistants better context.</p></div>{message&&<p className="feedback success" role="status">{message}</p>}{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={busy} aria-busy={busy}>{busy&&<span className="button-spinner" aria-hidden="true"/>}{busy?"Saving changes":"Save financial profile"}</button></div><p className="safety-copy">Never enter bank passwords, card numbers, or brokerage credentials.</p></aside>
 </form>}
 </main></Protected>;
}
