"use client";

import { FormEvent, useEffect, useState } from "react";
import { Protected } from "@/components/Protected";
import { api } from "@/lib/api";

type UserProfile={display_name:string;preferred_currency:string;timezone:string;financial_literacy:string;avatar_url:string|null};
type FinancialProfile={monthly_income:number;monthly_expenses:number;current_savings:number;monthly_investment:number;risk_tolerance:string;investment_horizon_months:number;goals:Array<{id?:string;name:string;target_amount:number;current_amount:number}>};
const initialUser:UserProfile={display_name:"",preferred_currency:"USD",timezone:"UTC",financial_literacy:"beginner",avatar_url:null};
const initialFinancial:FinancialProfile={monthly_income:0,monthly_expenses:0,current_savings:0,monthly_investment:0,risk_tolerance:"moderate",investment_horizon_months:60,goals:[]};

export default function ProfilePage(){
 const [profile,setProfile]=useState(initialUser);const [financial,setFinancial]=useState(initialFinancial);const [message,setMessage]=useState("");const [error,setError]=useState("");
 useEffect(()=>{Promise.all([api<UserProfile>("/profile"),api<FinancialProfile>("/financial-profile")]).then(([p,f])=>{setProfile(p);setFinancial(f);}).catch(e=>setError(e instanceof Error?e.message:"Unable to load profile"));},[]);
 async function save(e:FormEvent){e.preventDefault();setMessage("");setError("");try{await Promise.all([api("/profile",{method:"PUT",body:JSON.stringify(profile)}),api("/financial-profile",{method:"PUT",body:JSON.stringify(financial)})]);setMessage("Profile saved. Dashboard metrics now use these values.");}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save");}}
 function numberField(key:keyof Pick<FinancialProfile,"monthly_income"|"monthly_expenses"|"current_savings"|"monthly_investment"|"investment_horizon_months">,label:string){return <div className="field"><label htmlFor={key}>{label}</label><input id={key} type="number" min="0" step={key==="investment_horizon_months"?"1":"0.01"} value={financial[key]} onChange={e=>setFinancial({...financial,[key]:Number(e.target.value)})}/></div>}
 return <Protected><main className="container"><div className="page-head"><div><p className="eyebrow">Inputs, not judgments</p><h1>Your profile</h1></div><p className="lede">Use approximate monthly figures. Never enter bank passwords, card details, or brokerage credentials.</p></div><form className="grid profile-grid" onSubmit={save}><section className="card"><h2 style={{fontSize:38}}>Preferences</h2><div className="field"><label htmlFor="display_name">Display name</label><input id="display_name" value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})}/></div><div className="field"><label htmlFor="currency">Currency</label><input id="currency" minLength={3} maxLength={3} value={profile.preferred_currency} onChange={e=>setProfile({...profile,preferred_currency:e.target.value.toUpperCase()})}/></div><div className="field"><label htmlFor="literacy">Financial familiarity</label><select id="literacy" value={profile.financial_literacy} onChange={e=>setProfile({...profile,financial_literacy:e.target.value})}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></div></section><section className="card"><h2 style={{fontSize:38}}>Monthly picture</h2><div className="field-grid">{numberField("monthly_income","Income")}{numberField("monthly_expenses","Expenses")}{numberField("current_savings","Liquid savings")}{numberField("monthly_investment","Planned monthly investing")}{numberField("investment_horizon_months","Investment horizon (months)")}<div className="field"><label htmlFor="risk">Risk tolerance</label><select id="risk" value={financial.risk_tolerance} onChange={e=>setFinancial({...financial,risk_tolerance:e.target.value})}><option value="conservative">Conservative</option><option value="moderate">Moderate</option><option value="aggressive">Aggressive</option></select></div></div><p className="muted">The risk label is self-reported. It does not establish investment suitability or risk capacity.</p>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}<button className="button">Save profile</button></section></form></main></Protected>;
}

