"use client";

import { FormEvent, useState } from "react";
import { Protected } from "@/components/Protected";
import { api } from "@/lib/api";
import type { ChatReply, Entity } from "@/lib/types";

type Message={role:"user"|"assistant";content:string;intent?:string;engine?:string;entities?:Entity[];confidence?:number};

export default function ChatPage(){
 const [engine,setEngine]=useState<"rule-based"|"ai">("ai");const [input,setInput]=useState("");const [messages,setMessages]=useState<Message[]>([]);const [conversation,setConversation]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();const question=input.trim();if(!question||busy)return;setMessages(current=>[...current,{role:"user",content:question}]);setInput("");setBusy(true);setError("");try{const reply=await api<ChatReply>(`/chat/${engine}`,{method:"POST",body:JSON.stringify({message:question,conversation_id:conversation})});setConversation(reply.conversation_id);setMessages(current=>[...current,{role:"assistant",content:reply.response,intent:reply.intent,engine:reply.engine,entities:reply.entities,confidence:reply.confidence}]);}catch(cause){setError(cause instanceof Error?cause.message:"The assistant could not respond");}finally{setBusy(false);}}
 return <Protected><main className="chat-layout"><aside className="chat-side"><span className="eyebrow">Conversation mode</span><p className="muted">Compare deterministic keyword/entity matching with the intent-aware provider.</p><div className="engine-switch"><button className={engine==="rule-based"?"selected":""} onClick={()=>setEngine("rule-based")}><strong>Rule-based</strong><br/><small>Predictable and offline</small></button><button className={engine==="ai"?"selected":""} onClick={()=>setEngine("ai")}><strong>AI assistant</strong><br/><small>Mock-safe by default</small></button></div></aside><section className="chat-main"><div className="messages" aria-live="polite">{messages.length===0&&<div style={{maxWidth:620}}><p className="eyebrow">Ask one concrete question</p><h1 style={{fontSize:56}}>What do you want your money to do?</h1><p className="lede">Try “How large should my emergency fund be?” or “I want to avoid stocks—how else can I think about diversification?”</p></div>}{messages.map((m,index)=><article className={`message ${m.role}`} key={index}><div>{m.content}</div>{m.role==="assistant"&&<div className="meta"><span>{m.engine}</span><span>intent: {m.intent?.replaceAll("_"," ")}</span><span>confidence: {Math.round((m.confidence??0)*100)}%</span>{m.entities?.map((e,i)=><span key={`${e.type}-${i}`}>{e.type}: {e.value}</span>)}</div>}</article>)}{busy&&<article className="message assistant">Thinking carefully…</article>}{error&&<p className="error" role="alert">{error}</p>}</div><div className="composer"><form onSubmit={submit}><label className="field" style={{margin:0}}><span className="metric-label">Your finance question</span><input aria-label="Your finance question" value={input} onChange={e=>setInput(e.target.value)} maxLength={2000} placeholder="Ask about cash flow, savings, risk, goals…" /></label><button className="button" disabled={busy}>Send</button></form><small className="muted">Educational information only. No live prices, trades, or guaranteed returns.</small></div></section></main></Protected>;
}

